
#### Coursera: Statistical Inference Notes

##### Week1
1. Baye's Rule

$$
P(B|A) = \frac{P(A|B)P(B)}{P(A|B)P(B) + P(A|B^{c})P(B^{c})}
$$

2.   
__Sensititity__: the probability that the test is positive given that the subject actually has the disease, $P(+|D)$.  
__Specificity__: the probabiliyt that the test is negative that the subject does not have the disease, $P(-|D^{c})$.

3. Quantile
The $\alpha^{th}$ quantitle of a distribution with distribution function $F$ is the point $x_{\alpha}$ so that
$$F(x_{\alpha}) = \alpha$$
 - A percentile is simply a quantile with $\alpha$ expressed as a percent
 - The median is the $50^{th}$ percentile
 
 e.g.
 The $95^{th}$ percentile of a distribution is the point so that:  
  - the probability that a random variable drawn from the population is less is 95%
  - the probability that a random variable drawn from the populatoin is more is 5%

```{r}
 qbeta(0.5, 2, 1)
```
 
##### Week2

1. Variance Var(X) = E[(X-u)^2] = E[X^2] - E[X]^2

2. Sample variance 
$$S^2=\frac{\sum_{i=1}(X_{i} - \bar{X})^2}{n-1}$$


3. Calculate sample mean and variance given population mean and variance  
Sample mean :$E[\bar{x}] = \mu$   
Sample variance:$Var(\bar{X}) = \delta^2/n$  


4. Standard error $S/\sqrt{n}$: how variable averages of random samples of size n from the population are.


